INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20180038, 'ALCALA ISUIZA', 'ANGEL ADRIAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20202370, 'ARROYO LEON', 'DIEGO ENRIQUE');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20171869, 'BARDALES CHIHUANHUAYLLA', 'JORGE LUIS');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20192566, 'CARRION SAAVEDRA', 'DAVID RODRIGO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20202712, 'CARTOLIN YANQUE', 'MARIO ALEXANDER');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20184660, 'CUYA SANCHEZ', 'ANGEL OSCAR');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20200711, 'DUARTE ROMERO', 'ADRIAN'); 
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20194065, 'ESPINOZA ARROYO', 'JESUS MIGUEL');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20192303, 'GIL VELARDE', 'RAFAEL ALFONSO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20190857, 'GOMEZ LOPEZ', 'ALEJANDRO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20182686, 'GUILLEN CHARA', 'LUIS ANGELO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20142881, 'IZAGUIRRE CASTRO', 'ANDONI TOMAS');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20192985, 'LINARES ALZAMORA', 'RODRIGO GABRIEL');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20201166, 'LIVIAS VIGIL', 'AARON WAGNER LINCOLN'); 
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20202407, 'MENESES GUTIERREZ', 'HECTOR JOSE');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (30230242, 'MESTANZA CABRERA', 'AXEL SMITH');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20191291, 'MIGLIORI RUIZ', 'RENATO MARCELO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20191301, 'MIÑAN PANDURO', 'EDUARDO PATRICK');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20191412, 'OBLITAS MANTILLA', 'JOHAN ANDRES');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20152154, 'OROPEZA MEDRANO', 'BRAYAN JEANPIERE');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20191937, 'SOLIMANO PRINA', 'LEONARDO NAZIR');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20203668, 'SOTELO GOMEZ', 'FRANCO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20203703, 'TINCO BELLIDO', 'JEAN PIERRE');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20192003, 'TORRES BALMACEDA', 'SEBASTIAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20193553, 'TRUJILLO DELGADO', 'JANNIRE ASHLEY');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20162609, 'VARGAS AROSTEGUI', 'ERIK RICARDO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20172768, 'VELARDE HUAMAN', 'HECTOR EUSEBIO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20183460, 'ZAPATA ALBUJAR', 'PAOLO GIULIANO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20220227, 'AVILA DIAZ', 'GENESSI YAMILE');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224518, 'BARRETO IBRAHIM', 'REAID YUSEF');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224619, 'CASTAÑEDA MATEO', 'SHERLOCK CRISTOPHER');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20193934, 'CASTILLO SOLORZANO', 'JOAQUIN ALEJANDRO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20220600, 'CHAVEZ ESPINOZA', 'ANGELA FIORELLA');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20220604, 'CHAVEZ ORIHUELA', 'DANTE STHEFANO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224677, 'CONDOR VILCHEZ', 'DIANA'); 
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20220746, 'CUEVAS SERRATO', 'JORGE ADRIAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20220854, 'DIOSES SOLIS', 'RICARDO CESAR');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20220874, 'EGOAVIL CALDERON', 'FRANCO'); 
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224732, 'ELERA RIOS', 'ALEXIS FABIAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224782, 'GAMARRA ALMEYDA', 'CARLOS SEBASTIAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20221118, 'GONZALES IBARCENA', 'VALENTINA DAYANA');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224806, 'GUERRA ADRIANO', 'JOSE DARIO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224808, 'GUERRERO ANGASPILCO', 'FRANKLIN OWEN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224815, 'GUTIERREZ CADILLO', 'LUIS FRANCISCO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20221218, 'HERRERA NOEL', 'MAURICIO ALEJANDRO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20221290, 'ITURRIAGA VASQUEZ', 'FABRIZIO MIGUEL');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20221387, 'LINARES MATOS', 'MAURICIO ALONSO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20233916, 'LUNA MORAN', 'FRANCO ANTONIO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20221487, 'MAMANI MAGALLANES', 'MATIAS FERNANDO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20231730, 'MAQUEIRA BARCELLI', 'MELISSA');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20221543, 'MATSUMOTO ONAGA', 'LUCAS'); 
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224973, 'MERA INCIO', 'ALVARO DIEGO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20225019, 'NAKANDAKARI PACHERRE', 'KENYI JOSE');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20225024, 'NERI CAIPO', 'ELTON FABRIZIO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20221914, 'PAZ MARTINEZ', 'ALONSO SEBASTIAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20215189, 'PORTALES NUÑEZ', 'NILCER RENZO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20225158, 'QUISPE MAMANI', 'HANS ANTHONY');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20233847, 'RAMIREZ GUEVARA', 'AARON JARED');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20215241, 'RAMOS VELAZCO', 'HUMBERTO NEMESIO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20225176, 'REGUERA GARCIA', 'LUIS RUDY');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20225178, 'RENGIFO CALDERON', 'OSCAR MARTIN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20222306, 'SALAZAR ANGULO', 'GONZALO NICOLAS');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20222331, 'SALDARRIAGA MENDOZA', 'SEBASTIAN STEFANO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20225487, 'TANIGUCHI VENTURA', 'KATSUO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20222522, 'TIBURCIO MEJORADA', 'CLAUDIA JIMENA');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224131, 'TTITO ROFFINELLA', 'LEONARDO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20192057, 'VALIENTE APONTE', 'SEBASTIAN JULIO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20224203, 'YANCE VALENZUELA', 'ANTHONY');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20210076, 'ALFARO ECHEGARAY', 'JOAQUIN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20213214, 'ALFARO SANCHEZ', 'LUCIA ALEJANDRA');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20210120, 'ANGELES MUÑOZ', 'DAVID ANDRES');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20210457, 'CAMARA MORA', 'FANTINO ELIAS EMILIANO'); 
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20213383, 'CASTILLO PEÑA', 'ANGELES NICOLE');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20213418, 'CHAVEZ PRIETO', 'ALEKSEY SKRIABIN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20210670, 'CHURAMPI GUERRERO', 'ANDRES ANTHONY');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20213435, 'COCA DAVILA', 'KENNETT YAEL');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20213505, 'DIAZ VALLEJOS', 'WALTER ANDRÉS');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20210896, 'DUFFOO ANAMARIA', 'JOSE RODRIGO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20210981, 'FERNANDEZ CERNA', 'AARON BRYAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20210983, 'FERNANDEZ FALCON', 'ITALO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20211104, 'GARCIA VILCHEZ', 'CESAR ANDRES');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20213013, 'GONZALES NUÑEZ', 'LEANDRO PAOLO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20203082, 'JAUREGUI MENDOZA', 'LEONARDO GUSTAVO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20211454, 'LEON VILELA', 'PATRICK ALONSO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20211590, 'MAMANI VALVERDE', 'YERSON DANIEL');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20201271, 'MARROQUIN CUADRADO', 'AURISTELA ANGELA');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20211628, 'MARTINEZ RUEDA', 'LUIS MARIO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20211672, 'MEJIA APARCANA', 'ALESSANDER');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20213835, 'MEJORADA GALLARDO', 'ADRIANA SOFIA');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20194322, 'MEZA JACINTO', 'DIEGO ENRIQUE');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20203252, 'MONTES MAMANI', 'ANGELO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20211769, 'MORALES ACERO', 'DIEGO RAUL');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20201426, 'MORON LOAYZA', 'CESAR HERNAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20211918, 'ONAJA ADANIYA', 'KOHJI');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20211960, 'OVIEDO SOTO', 'GERSON ADEMIR');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20213996, 'PERALES SAN', 'MIGUEL DANTE JAASIEL'); 
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20214035, 'PUMAYUCRA CHAUCA', 'LUIS ANGEL');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20203475, 'RAMIREZ DE LA CUBA', 'CAROLINA ALEXANDRA'); 
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20184344, 'RAMIREZ MILLA', 'MAURICIO JESUS');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20214398, 'RAMIREZ PEREZ', 'ERNESTO ALDAIR');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20204876, 'RODRIGUEZ HUAMANLAZO', 'RENZO IVAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20201824, 'RODRIGUEZ SAENZ', 'ANGELO FABIAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20191931, 'SISNIEGAS SANCHEZ', 'ISAAC GABRIEL');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20212604, 'SOTERO HUAROTO', 'HIDEKI SEBASTIAN');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20214404, 'TAYPE ROJAS', 'DANIEL ALONSO');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20212700, 'TORRES RIVERA', 'ROLANDO JESUS');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20202143, 'VALDERRAMA URBAY', 'ERICK DMITRI');
INSERT INTO miembros (codigo, apellidos, nombres) VALUES (20212903, 'VILLALVA GOMEZ', 'DIANA SOFIA');